// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa_API.Store;

#nullable disable

namespace Villa_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Amenidad = "Piscina, Wi-Fi, Aire acondicionado",
                            Created_at = new DateTime(2024, 6, 18, 14, 11, 50, 220, DateTimeKind.Local).AddTicks(7454),
                            Detalle = "Una hermosa villa con vista al mar",
                            ImagenUrl = "http://ejemplo.com/imagen.jpg",
                            MetrosCuadrados = 150,
                            Name = "Villa Maravilla",
                            Ocupantes = 4,
                            Tarifa = 300.5,
                            Updated_at = new DateTime(2024, 6, 18, 14, 11, 50, 220, DateTimeKind.Local).AddTicks(7467)
                        },
                        new
                        {
                            Id = 12,
                            Amenidad = "Jacuzzi, Sauna, Gimnasio, Wi-Fi",
                            Created_at = new DateTime(2024, 6, 18, 14, 11, 50, 220, DateTimeKind.Local).AddTicks(7471),
                            Detalle = "Un retiro tranquilo con acceso privado a la playa",
                            ImagenUrl = "http://ejemplo.com/villa-solyplaya.jpg",
                            MetrosCuadrados = 200,
                            Name = "Villa Sol y Playa",
                            Ocupantes = 6,
                            Tarifa = 450.75,
                            Updated_at = new DateTime(2024, 6, 18, 14, 11, 50, 220, DateTimeKind.Local).AddTicks(7471)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
